export const get_SelectDriverList_sucess='get_SelectDriverList_sucess'
export const get_SelectDriverList_waiting='get_SelectDriverList_waiting'
export const get_SelectDriverList_failed='get_SelectDriverList_failed'
export const get_SelectDriverList_error='get_SelectDriverList_error'