export const get_carInfoRecord_success = 'get_carInfoRecord_success'
export const get_carInfoRecord_failed = 'get_carInfoRecord_failed'
export const get_carInfoRecord_waiting = 'get_carInfoRecord_waiting'
export const get_carInfoRecord_error = 'get_carInfoRecord_error'
export const get_carInfoRecord_resetStatus = 'get_carInfoRecord_resetStatus'