export const upload_DamageImage_success = 'upload_DamageImage_success'
export const upload_DamageImage_partSuccess = 'upload_DamageImage_partSuccess'
export const upload_DamageImage_waiting = 'upload_DamageImage_waiting'
export const upload_DamageImage_failed = 'upload_DamageImage_failed'
export const upload_DamageImage_error = 'upload_DamageImage_error'
