export const get_carDetail_success = 'get_carDetail_success'
export const get_carDetail_failed = 'get_carDetail_failed'
export const get_carDetail_waiting = 'get_carDetail_waiting'
export const get_carDetail_error = 'get_carDetail_error'
// export const get_carDetail_resetStatus = 'get_carDetail_resetStatus'