export const get_DamageImageList_success = 'get_DamageImageList_success'
export const get_DamageImageList_failed = 'get_DamageImageList_failed'
export const get_DamageImageList_error = 'get_DamageImageList_error'
export const get_DamageImageList_waiting = 'get_DamageImageList_waiting'

export const upload_ImageAtDemage_success = 'upload_ImageAtDemage_success'
export const upload_ImageAtDemage_partSuccess = 'upload_ImageAtDemage_partSuccess'
export const upload_ImageAtDemage_waiting = 'upload_ImageAtDemage_waiting'
export const upload_ImageAtDemage_failed = 'upload_ImageAtDemage_failed'
export const upload_ImageAtDemage_error = 'upload_ImageAtDemage_error'